services:
  - type: web
    name: hashcod-did-web
    runtime: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
